#!/bin/sh

set -e

addusers() {
  if [ -d /$1/sysusers.d ]; then
    pushd /$1/sysusers.d >/dev/null
    for f in $(find . -mindepth 1 -maxdepth 1 -type f); do
      /usr/bin/sysusers $f
    done
    popd >/dev/null
  fi
}

pushd /usr/lib/sysusers.d/
  /usr/bin/sysusers basic.conf
popd

addusers usr/lib
addusers etc
addusers run
