#!/bin/sh

addusers() {
  if [ -d /$1/sysusers.d ]; then
    pushd /$1/sysusers.d >/dev/null
    for f in $(find . -mindepth 1 -maxdepth 1 -type f); do
      /usr/bin/sysusers $f
    done
    popd >/dev/null
  fi
}

addusers usr/lib
addusers etc
addusers run
